version: 0.0
os: linux
files:
  - source: ./files/
    destination: /webcontent/

hooks:
  BeforeInstall:
    - location: scripts/webserver-stop.sh
  AfterInstall:
    - location: scripts/sleep.sh
    - location: scripts/webserver-restart.sh
