version: '3'

services:
  deploydocker1:
    build: ./website
    volumes:
      - ./website:/usr/app
    ports:
      - "1111:80"
  deploydocker2:
    build: ./website
    volumes:
      - ./website:/usr/app
    ports:
      - "2222:80"
  deploydocker3:
    build: ./website
    volumes:
      - ./website:/usr/app
    ports:
      - "3333:80"

